name: Simple CI (No Docker)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: nexedu_test
          POSTGRES_PASSWORD: test123
          POSTGRES_DB: nexedu_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Build application
        run: npm run build

      - name: Run tests with database
        env:
          DATABASE_URL: postgresql://nexedu_test:test123@localhost:5432/nexedu_test
        run: |
          npx prisma migrate deploy
          npm test

      - name: Upload build artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: nexedu-build-${{ github.sha }}
          path: |
            dist/
            package.json
            prisma/
          retention-days: 7
